package.json
src/components/Checkbox.css
src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/Heatmap.css
src/components/Heatmap.jsx
src/components/MainSection.jsx
src/components/SideSection.jsx
src/components/StreakList.jsx
tailwind.config.js
yarn.lock

Add react-calendar-heatmap
Add react-tooltip
Add yearly habit heatmap
Add greeting header
Redesign checkoff list

Redesign main section

---

src/App.js
src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/MainSection.jsx
src/components/StreakList.jsx

Add longest streak panel
Add longest streak leaderboard table

Design streak display

---

src/App.js
src/components/StreakList.jsx

Add useState
Show longest streak when collapsed
Show top 5 longest streaks when expanded

Add expandable streak list

---

src/App.js
src/components/Habit.jsx
src/components/Habits.jsx
src/components/SideSection.jsx
src/components/StreakList.jsx
src/components/TitleLogo.jsx

Will need to rename Habits to HabitList but not sure how

Add Habit, Modify Habits, SideSection, TitleLogo

---

src/components/MainSection.jsx
src/components/StreakList.jsx

Show 'Good morning' from 5 to 12
Show 'Good afternoon' from 12 to 19
Show 'Good evening' elsewhere

Add conditional greeting

---

src/components/CheckOffPanel.jsx
src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/HabitContent.jsx
src/components/HomeContent.jsx

Change CheckOff to Checkoff

---

src/components/Habit.jsx
src/components/HabitList.jsx
src/components/HabitPanel.jsx
src/components/SearchBar.jsx

Add search bar component and display it from HabitList. Habit change color when hovered over.

Add Search bar, display in HabitList

---

src/components/HabitHeatmap.jsx
src/components/HomeContent.jsx
src/components/MainHeatmap.jsx
src/components/TimeStatus.jsx

Add scroll feature

---

src/App.js
src/components/AuthContainer.jsx
src/components/AuthInput.jsx

Add AuthInput and AuthContainer
Frontend Styling
Changed all instances of class to className

Add AuthInput and AuthContainer

---

package.json
src/App.js
src/components/AuthContainer.jsx
src/components/AuthInput.jsx
src/firebase.js
src/pages/login.js
src/pages/signup.js
yarn.lock

Change signup.js and login.js to uppercase to properly use them
Frontend coding of Signup and Login
Minor frontend changes to AuthContainer and AuthInput
Add firebase, configuration setting keys as local environment variables, firebase.js

Add Signup.js and Login.js and Firebase

---

package.json
src/App.js
src/components/AuthContainer.jsx
src/components/AuthInput.jsx
src/firebase.js
src/pages/login.js
src/pages/signup.js
yarn.lock

Authentication and adjust firebase.js, login.js, signup.js

---

src/components/HabitContent.jsx
src/components/HabitHeatmap.jsx
src/components/HomeContent.jsx

Change style of habit page components
Click heatmap squares to set value

Edit habit page components

---

src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/HabitContent.jsx

Map habits to each checkoff on the home page
Habit name displayed on checkoff on habit page

Dynamically render checkoff

---

src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/HabitContent.jsx
src/components/HabitHeatmap.jsx
src/components/HomeContent.jsx

Clicking on a square will allow user to change data for that date
Clicking the checkbox will allow user to show if they completed the habit on the certain date or not
Setting completed to true for a certain date fills in square with green
Setting completed to false for a certain date fills in square with white

Add functional checkbox

---

src/components/HabitList.jsx
src/components/NewHabitContent.jsx
src/firebase.js

Use setDoc in firebase.js and make a new function
Set function in button in NewHabitContent.jsx

Connect to firebase with sendHabitToFirestore function

---

src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/HabitContent.jsx
src/components/HabitHeatmap.jsx
src/components/HomeContent.jsx

Checkoff component now works on home page
Reorganized some files to be easier to read

Add working checkoff for home page

---

src/components/AuthInput.jsx
src/components/Checkoff.jsx
src/components/HabitContent.jsx
src/components/SearchBar.jsx
src/pages/Login.js
src/pages/Signup.js

Set checkbox to read only
Fill in box depending on if habit is completed
Also fixed warning by changing class to className

Fix checkbox warning

---

src/components/HabitList.jsx
src/components/NewHabitContent.jsx

Fixed habit_name to name in NewHabitContent and hardcoded the QTKVV... path into HabitList

Dynamically display habits in sidebar

---

src/components/AuthContainer.jsx

Clicking on button takes you to home page (which it shouldn't if you aren't logged in)
It also causes the app to crash
I replaced it with a div component with a string

Make login auth logo button into a div

---

src/components/AuthContainer.jsx
src/components/Checkoff.css
src/components/HabitHeatmap.jsx
src/components/HabitPanel.jsx
src/components/HomeContent.jsx
src/components/NewHabitContent.jsx
src/components/TitleLogo.jsx
src/firebase.js
src/pages/Login.js
src/pages/Signup.js

Add dark green color to add a habit button on hover

Add button hover color

---

src/components/HabitList.jsx

Add Megan's scroll feature for the side section

add side section scroll

---

src/components/HomeContent.jsx
src/firebase.js

When you create a new habit, calendar data is associated with it
Data consists of an array of dates associated with false
values for completed

Initialize habit data with values for the year

---

src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/CheckoffPanel.jsx
src/components/HomeContent.jsx
src/components/MainSection.jsx
src/components/SearchBar.jsx

Make components closer together
Make size of "track your progress" bar not dependent on
length of quote

Fix design flaws

---

src/App.js
src/firebase.js
src/pages/Login.js
src/pages/Signup.js

Add login function in firebase.js
Add handleLogin function and button in Login.js and Signup.js

Add logout button on login and signup pages

---

src/App.js
src/components/CheckoffList.jsx
src/components/GreetingPanel.jsx

Remove requireAuth code and checkoff list uses current user id

Remove requireAuth, fix checkoffList

---

src/components/CheckoffList.jsx
src/components/HabitHeatmap.jsx
src/firebase.js

Fixed issue where a null value was being displayed
Had to edit code to initialize values
Fix heatmap date display

Fix calendar heatmap display

---

src/components/Checkoff.jsx
src/components/CheckoffList.jsx
src/components/HabitContent.jsx
src/firebase.js

When you click checkoff then it sends the changed to firebase

Push updatedCalender data to firebase

---

src/components/AuthContainer.jsx
src/pages/Login.js
src/pages/Signup.js

Remove "Log out" buttons from login and signup pages. Fix padding in AuthContainer

Update login/signup frontend

---

src/pages/Login.js
src/pages/Signup.js

delete unecessary confirm password
added navigation button from login to signup
edited error messages

Login and Signup page touch ups

---

src/App.js
src/components/HomeContent.jsx
src/contexts/AuthContext.js
src/firebase.js

Add redirecting to pages based on user authentication status
-> Login if not logged in
-> / if logged in

Add Auth Redirecting

---

src/pages/Signup.js

Add "already have an account. log in" button to take you from
sign up page to login page

Add redirect from signup to login

---

src/components/HomeContent.jsx
src/pages/Login.js

Changed log in button so that it's lighter colored and gets darker when hovered over
Now matching sign up button

Fix log in button hover color

---

src/App.js
src/components/AuthContainer.jsx
src/pages/Login.js
src/pages/Signup.js

Make the pages prettier
Drop shadow + green color added

Add design details to login/signup
